apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  labels:
    app: backend
    component: api-server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend
      component: api-server
