apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  labels:
    app: backend
    component: api-server
  annotations:
    iam.gke.io/gcp-service-account: api-server-dev@PROJECT_ID.iam.gserviceaccount.com
