apiVersion: v1
kind: ServiceAccount
metadata:
  name: finance-api
  labels:
    app: finance-api
  annotations:
    iam.gke.io/gcp-service-account: finance-api-sa@lifenav-prod.iam.gserviceaccount.com
