// Auto-generated by `supabase gen types typescript`
// Run `pnpm db:gen-types` to regenerate after schema changes
//
// Placeholder until Supabase project is connected.
// This file will be replaced by the actual generated types.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string | null
          display_name: string | null
          avatar_url: string | null
          role: string
          pilot_role: string
          pilot_enabled: boolean
          user_type: string
          setup_completed: boolean
          subscription_tier: string
          theme: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email?: string | null
          display_name?: string | null
          avatar_url?: string | null
          role?: string
          pilot_role?: string
          pilot_enabled?: boolean
          user_type?: string
          setup_completed?: boolean
          subscription_tier?: string
          theme?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          display_name?: string | null
          avatar_url?: string | null
          role?: string
          pilot_role?: string
          pilot_enabled?: boolean
          user_type?: string
          setup_completed?: boolean
          subscription_tier?: string
          theme?: string
          updated_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
