apiVersion: v1
kind: ServiceAccount
metadata:
  name: imgproxy
  labels:
    app: imgproxy
    component: image-processor
    app.kubernetes.io/name: imgproxy
  annotations:
    iam.gke.io/gcp-service-account: imgproxy@lifenav-prod.iam.gserviceaccount.com
