"""
GraphRAG gRPC Client.

Provides async interface to the Rust GraphRAG service for:
- Hybrid knowledge graph + vector RAG queries
- Semantic search in knowledge graphs
- Vector similarity search
- Entity and relationship queries
"""

from typing import Any, AsyncIterator, Optional
from contextlib import asynccontextmanager

import grpc
from grpc import aio

from app.core.config import settings
from app.core.logging import logger

# Import generated protobuf stubs
# Note: These will be generated by running backend/scripts/generate_proto.sh
try:
    from app.proto import graphrag_pb2, graphrag_pb2_grpc
except ImportError:
    # Fallback for when proto hasn't been generated yet
    logger.warning(
        "GraphRAG proto files not generated. Run: backend/scripts/generate_proto.sh"
    )
    graphrag_pb2 = None  # type: ignore
    graphrag_pb2_grpc = None  # type: ignore


class GraphRAGClient:
    """
    Async gRPC client for GraphRAG service.

    Features:
    - Connection pooling via persistent channel
    - Automatic retry with exponential backoff
    - Health checking
    - Timeout configuration
    - Context-aware queries (tenant_id, user_id for RLS)

    Usage:
        async with GraphRAGClient() as client:
            response = await client.query_personalized(
                query="What are my financial goals?",
                user_id="123",
                tenant_id="456"
            )
    """

    def __init__(
        self,
        host: str | None = None,
        port: int | None = None,
        timeout: float = 30.0,
        max_retries: int = 3,
    ):
        """
        Initialize GraphRAG client.

        Args:
            host: GraphRAG service host (defaults to settings.GRAPHRAG_HOST)
            port: GraphRAG service port (defaults to settings.GRAPHRAG_PORT)
            timeout: Request timeout in seconds
            max_retries: Maximum number of retry attempts
        """
        self.host = host or getattr(settings, "GRAPHRAG_HOST", "localhost")
        self.port = port or getattr(settings, "GRAPHRAG_PORT", 50051)
        self.timeout = timeout
        self.max_retries = max_retries
        self.address = f"{self.host}:{self.port}"

        self._channel: Optional[aio.Channel] = None
        self._stub: Optional[Any] = None

    async def connect(self) -> None:
        """Establish gRPC channel connection."""
        if self._channel is not None:
            return

        # Create async gRPC channel
        self._channel = aio.insecure_channel(
            self.address,
            options=[
                ("grpc.max_send_message_length", 100 * 1024 * 1024),  # 100 MB
                ("grpc.max_receive_message_length", 100 * 1024 * 1024),  # 100 MB
                ("grpc.keepalive_time_ms", 30000),  # 30 seconds
                ("grpc.keepalive_timeout_ms", 10000),  # 10 seconds
            ],
        )

        # Create stub
        if graphrag_pb2_grpc:
            self._stub = graphrag_pb2_grpc.GraphRAGStub(self._channel)

        logger.info(f"Connected to GraphRAG service at {self.address}")

    async def close(self) -> None:
        """Close gRPC channel."""
        if self._channel:
            await self._channel.close()
            self._channel = None
            self._stub = None
            logger.info("Closed GraphRAG service connection")

    @asynccontextmanager
    async def _get_stub(self):
        """Context manager for getting stub with connection check."""
        if self._stub is None:
            await self.connect()
        yield self._stub

    async def health_check(self) -> dict[str, Any]:
        """
        Check GraphRAG service health.

        Returns:
            Health status dict with service availability
        """
        try:
            async with self._get_stub() as stub:
                request = graphrag_pb2.HealthCheckRequest()
                response = await stub.HealthCheck(request, timeout=5.0)

                return {
                    "status": response.status,
                    "services": dict(response.services),
                    "version": response.version,
                    "connected": True,
                }
        except grpc.RpcError as e:
            logger.error(f"GraphRAG health check failed: {e}")
            return {
                "status": "unhealthy",
                "connected": False,
                "error": str(e),
            }

    async def query_personalized(
        self,
        query: str,
        user_id: str,
        tenant_id: str,
        max_results: int = 10,
        domains: list[str] | None = None,
        include_sources: bool = True,
        include_reasoning: bool = False,
    ) -> dict[str, Any]:
        """
        Query with RAG in personalized mode (with RLS filtering).

        Args:
            query: Natural language query
            user_id: User ID for RLS filtering
            tenant_id: Tenant ID for multi-tenancy
            max_results: Maximum number of results
            domains: Filter by domains (finance, health, etc.)
            include_sources: Include source attribution
            include_reasoning: Include reasoning steps

        Returns:
            Query response with answer, sources, and entities
        """
        try:
            async with self._get_stub() as stub:
                request = graphrag_pb2.PersonalizedQueryRequest(
                    query=query,
                    user_id=user_id,
                    tenant_id=tenant_id,
                    max_results=max_results,
                    domains=domains or [],
                    include_sources=include_sources,
                    include_reasoning=include_reasoning,
                )

                response = await stub.QueryPersonalized(request, timeout=self.timeout)

                return {
                    "answer": response.answer,
                    "sources": [self._source_to_dict(s) for s in response.sources],
                    "reasoning": [self._reasoning_to_dict(r) for r in response.reasoning],
                    "confidence": response.confidence,
                    "entities": [self._entity_to_dict(e) for e in response.entities],
                    "duration_ms": response.duration_ms,
                }
        except grpc.RpcError as e:
            logger.error(f"GraphRAG personalized query failed: {e}")
            raise

    async def query_centralized(
        self,
        query: str,
        max_results: int = 10,
        domains: list[str] | None = None,
        include_sources: bool = True,
        include_reasoning: bool = False,
    ) -> dict[str, Any]:
        """
        Query with RAG in centralized mode (org-wide knowledge).

        Args:
            query: Natural language query
            max_results: Maximum number of results
            domains: Filter by domains
            include_sources: Include source attribution
            include_reasoning: Include reasoning steps

        Returns:
            Query response with answer, sources, and entities
        """
        try:
            async with self._get_stub() as stub:
                request = graphrag_pb2.QueryRequest(
                    query=query,
                    max_results=max_results,
                    domains=domains or [],
                    include_sources=include_sources,
                    include_reasoning=include_reasoning,
                )

                response = await stub.QueryCentralized(request, timeout=self.timeout)

                return {
                    "answer": response.answer,
                    "sources": [self._source_to_dict(s) for s in response.sources],
                    "reasoning": [self._reasoning_to_dict(r) for r in response.reasoning],
                    "confidence": response.confidence,
                    "entities": [self._entity_to_dict(e) for e in response.entities],
                    "duration_ms": response.duration_ms,
                }
        except grpc.RpcError as e:
            logger.error(f"GraphRAG centralized query failed: {e}")
            raise

    async def semantic_search(
        self,
        query: str,
        tenant_id: str,
        entity_type: str | None = None,
        limit: int = 10,
    ) -> dict[str, Any]:
        """
        Semantic search in knowledge graph (SPARQL-based).

        Args:
            query: Search query
            tenant_id: Tenant ID for isolation
            entity_type: Filter by entity type (ln:Goal, ln:Transaction, etc.)
            limit: Maximum number of results

        Returns:
            Search results with entities
        """
        try:
            async with self._get_stub() as stub:
                request = graphrag_pb2.SemanticSearchRequest(
                    query=query,
                    entity_type=entity_type or "",
                    limit=limit,
                    tenant_id=tenant_id,
                )

                response = await stub.SemanticSearch(request, timeout=self.timeout)

                return {
                    "entities": [self._entity_to_dict(e) for e in response.entities],
                    "total_count": response.total_count,
                    "duration_ms": response.duration_ms,
                }
        except grpc.RpcError as e:
            logger.error(f"GraphRAG semantic search failed: {e}")
            raise

    async def vector_search(
        self,
        query_text: str,
        limit: int = 10,
        min_score: float = 0.5,
    ) -> dict[str, Any]:
        """
        Vector similarity search.

        Args:
            query_text: Text to embed and search
            limit: Maximum number of results
            min_score: Minimum similarity score (0.0-1.0)

        Returns:
            Vector search results
        """
        try:
            async with self._get_stub() as stub:
                request = graphrag_pb2.VectorSearchRequest(
                    query_text=query_text,
                    limit=limit,
                    min_score=min_score,
                )

                response = await stub.VectorSearch(request, timeout=self.timeout)

                return {
                    "results": [self._vector_result_to_dict(r) for r in response.results],
                    "duration_ms": response.duration_ms,
                }
        except grpc.RpcError as e:
            logger.error(f"GraphRAG vector search failed: {e}")
            raise

    async def hybrid_search(
        self,
        query: str,
        tenant_id: str,
        limit: int = 10,
        semantic_weight: float = 0.6,
        vector_weight: float = 0.4,
    ) -> dict[str, Any]:
        """
        Hybrid search combining semantic + vector search.

        Args:
            query: Search query
            tenant_id: Tenant ID for isolation
            limit: Maximum number of results
            semantic_weight: Weight for semantic results (0.0-1.0)
            vector_weight: Weight for vector results (0.0-1.0)

        Returns:
            Hybrid search results with combined scores
        """
        try:
            async with self._get_stub() as stub:
                request = graphrag_pb2.HybridSearchRequest(
                    query=query,
                    limit=limit,
                    tenant_id=tenant_id,
                    semantic_weight=semantic_weight,
                    vector_weight=vector_weight,
                )

                response = await stub.HybridSearch(request, timeout=self.timeout)

                return {
                    "results": [self._hybrid_result_to_dict(r) for r in response.results],
                    "duration_ms": response.duration_ms,
                }
        except grpc.RpcError as e:
            logger.error(f"GraphRAG hybrid search failed: {e}")
            raise

    # Helper methods for converting protobuf messages to dicts

    def _entity_to_dict(self, entity) -> dict[str, Any]:
        """Convert Entity proto to dict."""
        return {
            "uri": entity.uri,
            "type": entity.type,
            "label": entity.label,
            "properties": dict(entity.properties),
            "tenant_id": entity.tenant_id,
            "created_at": entity.created_at,
            "updated_at": entity.updated_at,
        }

    def _source_to_dict(self, source) -> dict[str, Any]:
        """Convert Source proto to dict."""
        return {
            "source_type": source.source_type,
            "source_uri": source.source_uri,
            "content": source.content,
            "relevance": source.relevance,
            "metadata": dict(source.metadata),
        }

    def _reasoning_to_dict(self, reasoning) -> dict[str, Any]:
        """Convert ReasoningStep proto to dict."""
        return {
            "step": reasoning.step,
            "description": reasoning.description,
            "action": reasoning.action,
            "result": reasoning.result,
        }

    def _vector_result_to_dict(self, result) -> dict[str, Any]:
        """Convert VectorResult proto to dict."""
        return {
            "id": result.id,
            "score": result.score,
            "content": result.content,
            "metadata": dict(result.metadata),
        }

    def _hybrid_result_to_dict(self, result) -> dict[str, Any]:
        """Convert HybridResult proto to dict."""
        return {
            "entity": self._entity_to_dict(result.entity) if result.entity else None,
            "semantic_score": result.semantic_score,
            "vector_score": result.vector_score,
            "combined_score": result.combined_score,
            "matched_by": result.matched_by,
        }

    # Context manager support
    async def __aenter__(self):
        """Async context manager entry."""
        await self.connect()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Async context manager exit."""
        await self.close()


# Global client instance (reuse connections)
_graphrag_client: Optional[GraphRAGClient] = None


def get_graphrag_client() -> GraphRAGClient:
    """
    Get or create global GraphRAG client instance.

    Returns:
        Shared GraphRAG client (connection pooling)
    """
    global _graphrag_client
    if _graphrag_client is None:
        _graphrag_client = GraphRAGClient()
    return _graphrag_client
