"""add integration platform and user integration tables

Revision ID: c7fddc84529c
Revises: add_health_insurance_tables
Create Date: 2025-11-08 21:35:53.273189

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7fddc84529c'
down_revision: Union[str, None] = 'add_health_insurance_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('health_insurance', 'insurance_type',
               existing_type=postgresql.ENUM('health', 'dental', 'vision', 'life', 'disability', name='insurancetype'),
               nullable=True)
    op.drop_index('ix_health_insurance_is_active', table_name='health_insurance')
    op.alter_column('insurance_claims', 'status',
               existing_type=postgresql.ENUM('submitted', 'processing', 'approved', 'denied', 'paid', 'appealed', name='claimstatus'),
               nullable=True)
    op.drop_index('ix_insurance_claims_claim_number', table_name='insurance_claims')
    op.drop_index('ix_insurance_claims_insurance_id', table_name='insurance_claims')
    op.drop_index('ix_insurance_claims_status', table_name='insurance_claims')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_insurance_claims_status', 'insurance_claims', ['status'], unique=False)
    op.create_index('ix_insurance_claims_insurance_id', 'insurance_claims', ['insurance_id'], unique=False)
    op.create_index('ix_insurance_claims_claim_number', 'insurance_claims', ['claim_number'], unique=False)
    op.alter_column('insurance_claims', 'status',
               existing_type=postgresql.ENUM('submitted', 'processing', 'approved', 'denied', 'paid', 'appealed', name='claimstatus'),
               nullable=False)
    op.create_index('ix_health_insurance_is_active', 'health_insurance', ['is_active'], unique=False)
    op.alter_column('health_insurance', 'insurance_type',
               existing_type=postgresql.ENUM('health', 'dental', 'vision', 'life', 'disability', name='insurancetype'),
               nullable=False)
    # ### end Alembic commands ###
