apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamav-signatures-pvc
  labels:
    app: clamav
    component: antivirus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard-rwo
