#!/bin/bash
PROJECT_ID="lifenav-prod"
PROJECT_NUMBER="816649286806"
POOL_NAME="github-pool"
PROVIDER_NAME="github-provider"
SA_NAME="terraform-deployer"
GITHUB_ORG="Life-Navigator"

echo "Step 2 (retry): Creating OIDC Provider with attribute condition..."
gcloud iam workload-identity-pools providers create-oidc $PROVIDER_NAME --project=$PROJECT_ID --location="global" --workload-identity-pool=$POOL_NAME --display-name="GitHub Provider" --attribute-mapping="google.subject=assertion.sub,attribute.actor=assertion.actor,attribute.repository=assertion.repository,attribute.repository_owner=assertion.repository_owner" --attribute-condition="assertion.repository_owner=='$GITHUB_ORG'" --issuer-uri="https://token.actions.githubusercontent.com"

echo ""
echo "Step 3 (retry): Granting impersonation permission..."
gcloud projects add-iam-policy-binding $PROJECT_ID --role="roles/iam.serviceAccountTokenCreator" --member="principalSet://iam.googleapis.com/projects/$PROJECT_NUMBER/locations/global/workloadIdentityPools/$POOL_NAME/attribute.repository_owner/$GITHUB_ORG"

echo ""
echo "============================================"
echo "Add these to GitHub Secrets:"
echo "============================================"
echo ""
echo "GCP_PROJECT_ID: lifenav-prod"
echo ""
echo "GCP_WORKLOAD_IDENTITY_PROVIDER: projects/816649286806/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
echo ""
echo "GCP_SERVICE_ACCOUNT: terraform-deployer@lifenav-prod.iam.gserviceaccount.com"
echo ""
