#!/bin/bash
SA="serviceAccount:terraform-deployer@lifenav-prod.iam.gserviceaccount.com"
gcloud projects add-iam-policy-binding lifenav-prod --member="$SA" --role="roles/editor"
gcloud projects add-iam-policy-binding lifenav-prod --member="$SA" --role="roles/iam.securityAdmin"
gcloud projects add-iam-policy-binding lifenav-prod --member="$SA" --role="roles/resourcemanager.projectIamAdmin"
gcloud projects add-iam-policy-binding lifenav-prod --member="$SA" --role="roles/container.admin"
gcloud projects add-iam-policy-binding lifenav-prod --member="$SA" --role="roles/cloudsql.admin"
gcloud projects add-iam-policy-binding lifenav-prod --member="$SA" --role="roles/secretmanager.admin"
gcloud projects add-iam-policy-binding lifenav-prod --member="$SA" --role="roles/storage.admin"
gcloud projects add-iam-policy-binding lifenav-prod --member="$SA" --role="roles/redis.admin"
gcloud projects add-iam-policy-binding lifenav-prod --member="$SA" --role="roles/compute.networkAdmin"
echo "All roles added successfully!"
