apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: huggingface-token
  labels:
    app: maverick
    component: embeddings
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: huggingface-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: huggingface-token-dev
